using BlazorAppDotNot8.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace BlazorAppDotNot8;

public abstract class EntityBase<T>: IAuditable where T : EntityBase<T>
{   
    public long Id { get; set; }
    
    public void Configure(EntityTypeBuilder<T> builder)
    {
        // Mark Id as the primary key
        builder.HasKey(c => c.Id);

        // Configure Id to be generated by the database
        builder.Property(c => c.Id)
            .ValueGeneratedOnAdd();  
    }
}